import io
import re
from pathlib import Path
from fpdf import FPDF

FONT_PATH = None
for candidate in [
    "C:/Windows/Fonts/msyh.ttc",
    "C:/Windows/Fonts/simsun.ttc",
    "C:/Windows/Fonts/simhei.ttf",
    "C:/Windows/Fonts/STSONG.TTF",
]:
    if Path(candidate).exists():
        FONT_PATH = candidate
        break


def generate_pdf_resume(content: str, candidate_name: str = "") -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    has_cjk = FONT_PATH is not None
    if has_cjk:
        pdf.add_font("cjk", "", FONT_PATH, uni=True)
        pdf.add_font("cjk", "B", FONT_PATH, uni=True)

    family = "cjk" if has_cjk else "Helvetica"

    # Header line
    pdf.set_draw_color(13, 148, 136)
    pdf.set_line_width(0.6)
    pdf.line(20, 18, 190, 18)

    # Parse sections
    sections = re.split(r"【(.+?)】", content)
    in_optimized = False

    for part in sections:
        part = part.strip()
        if not part:
            continue

        if part == "简历诊断":
            in_optimized = False
        elif part == "优化后简历":
            in_optimized = True
        elif part in ("优化对比", "HR视角点评"):
            in_optimized = False

        if not in_optimized:
            continue

        # Render the optimized resume content
        for line in part.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(4)
                continue

            # Strip any residual markdown
            line = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
            line = re.sub(r"^#+\s*", "", line)
            line = re.sub(r"^[-*]\s+", "· ", line)
            line = re.sub(r"`(.+?)`", r"\1", line)

            if line.startswith("· "):
                pdf.set_x(30)
                pdf.set_font(family, "", 10)
                pdf.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")
            else:
                pdf.set_font(family, "", 10)
                pdf.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.set_y(-25)
    pdf.set_draw_color(13, 148, 136)
    pdf.set_line_width(0.3)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.set_y(-20)
    pdf.set_font(family, "", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 10, "Generated by QuickHire AI", align="C")

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()
